### ISSUE TITLE
[bug] token.shareholders.mintToken: throws an error

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#124]
Node version: v10.17.0
SDK version: 2.0.1-beta.56
Code example:

```js
const { Polymath } = require('@polymathnetwork/sdk');
const web3Utils = require('web3-utils');

(async function() {
  const privateKey = 'PRIV_KEY';
  const networkId = 42;
  const symbol = 'RN'
  const delegateAddress = '0x1B2D2797A56c9eBa12aa821D643aB0dBa66C3772'

  const networkConfigs = {
    42: {
      polymathRegistryAddress: '0x5b215a7d39ee305ad28da29bf2f0425c6c2a00b3',
      providerUrl: 'https://kovan.polymath.network',
      privateKey
    },
  };
  const config = networkConfigs[networkId];
  const sdk = new Polymath();
  await sdk.connect(config);
  console.log('=== Connected')

  try {
    const token = await sdk.getSecurityToken({symbol});
    const amount = web3Utils.toBN('1000')
    console.log(`minting ${amount.toString()} tokens to ${delegateAddress}`)
    const q = await token.shareholders.mintTokens({mintingData: 
      [{
        address: delegateAddress,
        amount
      }]
    })
    const ret = await q.run()
    console.log('ret of mintTokens', ret)
  } catch(error) {
    console.error('Error', error);
  }
})();
```

**Error**:
```
Error TypeError: e.multipliedBy is not a function
    at multipliedBy (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/webpack:/@polymathnetwork/contract-wrappers/src/utils/convert.ts:72:16)
    at valueToWei (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/webpack:/@polymathnetwork/contract-wrappers/src/utils/convert.ts:77:12)
    at Array.map (<anonymous>)
    at map (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/webpack:/@polymathnetwork/contract-wrappers/src/utils/convert.ts:76:16)
    at t.<anonymous> (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/webpack:/@polymathnetwork/contract-wrappers/src/contract_wrappers/tokens/security_token_wrapper/common.ts:1667:7)
    at /Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/index.js:2130:1690
    at Object.next (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/index.js:2130:1795)
    at o (/Users/remon/projects/sdk-sandbox/node_modules/@polymathnetwork/contract-wrappers/lib/index.js:2130:541)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by VictorVicente** [comment]
Hey @remon-nashid, I think the problem here is that you're using BN.js library instead of bignumber.js. The SDK works with this last one. Could you try that?

**Comment by remon-nashid** [comment]
Hey @VictorVicente, I'm testing minting on a barebone project that only depends on SDK, and any big number library that it brings. I have to say that after inspecting the dependencies, it seems there are a couple of bn.js and bignumber.js instances, but all of them are dependencies of dependencies of the sdk.

Here are my direct dependencies:

```
  "dependencies": {
    "@polymathnetwork/sdk": "2.0.1-beta.56",
    "dotenv": "^8.2.0"
  }
```

And here are the instances of bignumber.js and bn.js, respectively:
```
Remons-MacBook-Pro:sdk-sandbox remon$ yarn list --pattern bignumber
yarn list v1.19.1
├─ @types/ethereum-protocol@1.0.0
│  └─ bignumber.js@7.2.1
├─ bignumber.js@8.0.2
└─ web3@0.20.2
   └─ bignumber.js@2.0.7
✨  Done in 0.70s.
Remons-MacBook-Pro:sdk-sandbox remon$ yarn list --pattern bn.js
yarn list v1.19.1
├─ @types/bn.js@4.11.5
├─ bn.js@4.11.8
├─ eth-lightwallet@3.0.1
│  └─ bn.js@2.2.0
├─ ethjs-unit@0.1.6
│  └─ bn.js@4.11.6
├─ number-to-bn@1.7.0
│  └─ bn.js@4.11.6
└─ rustbn.js@0.2.0
```

**Comment by remon-nashid** [comment]
Thanks @VictorVicente. Per our separate discussion, if SDK user needs to convert a number to bigNumber, they should import `BigNumber` from the SDK (as follows), rather than using`web3.utils.toBN`. 

```
const { Polymath, BigNumber } = require('@polymathnetwork/sdk');
const amount = new BigNumber('1000');
```

Closting this issue
